name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v7
        - name: List and Read File
          run: |
            echo "My First GitHub Actions Job"
            ls -ltra
            cat README.md
        - name: Generate ASCII Artwork
          run: cowsay -f dragon "Run for cover, I'm a DRAGON....RAWR!!" >> dragon.txt