name: Generate ASCII Artwork

on: push

jobs:
  Build_Job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Install cowsay program
      run: sudo apt-get install cowsay -y
    - name: Execute cowsay CMD
      run: cowsay -f dragon "Run for cover, I'm a DRAGON....RAWR!!" >> dragon.txt
    - name: Sleep for 10 Seconds
      run: sleep 10
  Test_Job_2:
    needs: Build_Job_1
    runs-on: ubuntu-latest
    steps:
    - name: Sleep for 5 Seconds
      run: sleep 5
    - name: Test file exists
      run: grep -i "dragon" dragon.txt
  Deploy_Job_3:
    needs: Test_Job_2
    runs-on: ubuntu-latest
    steps:
    - name: Read File
      run: cat dragon.txt
    - name: Deploying
      run: echo Deploying... .. .k