name: Generate ASCII Artwork

on:
    push

jobs:
    ascii_job:
        run-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v7
        - name: Install cowsay program
          run: sudo apt-get install cowsay -y
        - name: Execute cowsay CMD
          run: cowsay -f dragon "Run for cover, I'm a DRAGON....RAWR!!" >> dragon.txt
        - name: Test file exist
          run: grep -i "dragon" dragon.txt
        - name: Read File
          run: cat dragon.txt
        - name: List repo files
          run: ls -ltra