name: Generate ASCII Artwork

on: push

jobs:
  Build_Job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Install cowsay program
      run: sudo apt-get install cowsay -y
    - name: Execute cowsay CMD
      run: cowsay -f dragon "Run for cover, I'm a DRAGON....RAWR!!" >> dragon.txt
    - name: Upload dragon file
      uses: actions/upload-artifact@v7
      with:
        name: dragon-text-file
        path: dragon.txt
  Test_Job_2:
    needs: Build_Job_1
    runs-on: ubuntu-latest
    steps:
    - name: Download dragon file
      uses: actions/download-artifact@v8
      with:
        name: dragon-text-file
    - name: Test file exists
      run: grep -i "dragon" dragon.txt
  Deploy_Job_3:
    needs: Test_Job_2
    runs-on: ubuntu-latest
    steps:
    - name: Download dragon file
      uses: actions/download-artifact@v8
      with:
        name: dragon-text-file
    - name: Read File
      run: cat dragon.txt
    - name: Deploying
      run: echo Deploying... .. .k