name: Timeout minutes

on:
  push:

concurrency:
    group: production-group
    # cancel-in-progress: true    # Running one is Killed, new one starts
    cancel-in-progress: false     # New one stays "Pending" until the running one finishes
env:
    CONTAINER_REGISTRY: docker.io
    IMAGE_NAME: myubuntu
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
        - name: Docker Build
          run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:v1
        - name: Docker login
          run: echo docker login --username ${{ vars.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
        - name: Docker Publish
          run: echo docker push ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:v1
    deploy:
        needs: docker
        runs-on: ubuntu-latest
        timeout-minutes: 1      # HERE...!!
        steps:
        - name: Docker Run
          run: | 
            echo docker run -d -p 8080:80 ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:v1
            sleep 90s